ascii actions file

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,18 +1,48 @@
-name: Docker Image CI
+name: Generate ASCII Art
 
 on:
   push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+    branches:
+      - main
+  workflow_dispatch:
 
 jobs:
-
-  build:
-
+  generate-ascii:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Build the Docker image
-      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
+    - name: Checkout code
+      uses: actions/checkout@v3
+
+    - name: Install Cowsay Program
+      run: sudo apt-get install -y cowsay
+
+    - name: Execute Cowsay Program
+      run: |
+        cowsay -f dragon "Run for cover, I am a dragon!" >> dragon.txt
+
+    - name: Upload dragon.txt
+      uses: actions/upload-artifact@v3
+      with:
+        name: dragon-file
+        path: dragon.txt
+
+  test-and-read:
+    runs-on: ubuntu-latest
+    needs: generate-ascii
+
+    steps:
+    - name: Download dragon.txt
+      uses: actions/download-artifact@v3
+      with:
+        name: dragon-file
+
+    - name: Test File exists
+      run: |
+        grep -i "dragon" dragon.txt || echo "Dragon not found in file!"
+
+    - name: Read file
+      run: cat dragon.txt
+
+    - name: Checkout Repo Files
+      run: ls
